version: 2.1

orbs:
  aws-white-list-circleci-ip: configure/aws-white-list-circleci-ip@1.0.1

executors:
  docker-executor:
    docker:
      - image: circleci/android:api-28
    working_directory: ~/amplify-flutter

  macos-executor:
    macos:
      xcode: 11.6.0
    working_directory: ~/amplify-flutter

  publish-executor:
    docker:
      - image: circleci/ruby:2.6.6
    working_directory: ~/amplify-flutter

commands:
  install_flutter:
    description:
      Install Flutter and set up paths.
    parameters:
      flutter_branch:
        description: Flutter branch or version tag.
        type: string
        default: stable
    steps:
      - run:
          name: Set up Flutter
          command: |
            echo 'export FLUTTER_HOME=${HOME}/sdks/flutter' >> $BASH_ENV
            echo 'export FLUTTER_BRANCH=<< parameters.flutter_branch >>' >> $BASH_ENV
            echo 'export FLUTTER_ROOT=${FLUTTER_HOME}' >> $BASH_ENV
            echo 'export PATH=${PATH}:${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin:${HOME}/.pub-cache/bin:${FLUTTER_HOME}/.pub-cache/bin' >> $BASH_ENV
            source $BASH_ENV
            git clone --branch ${FLUTTER_BRANCH} https://github.com/flutter/flutter.git ${FLUTTER_HOME}
            (yes || true) | flutter doctor --android-licenses && flutter doctor

  install_melos:
    steps:
      - run:
          name: Install and set up melos
          command: |
            pub global activate melos
            ln -s ~/.pub-cache/hosted/http%58%47%47pub.kyleyan.io%584000 ~/.pub-cache/hosted/pub.dartlang.org
            melos bootstrap

  write_oauth_tokens:
    description:
      Write OAuth tokens to ~/.pub-cache/credentials.json
    steps:
      - run:
          name: Write Google OAuth Token
          command: |
            mkdir -p ~/.pub-cache
            cat \<<EOF > ~/.pub-cache/credentials.json
            {
              "accessToken":"$OAUTH_ACCESS_TOKEN",
              "refreshToken":"$OAUTH_REFRESH_TOKEN",
              "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
              "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
              "expiration": $OAUTH_EXPIRATION
            }
            EOF
  reset_pub_url:
    description:
      Reset the PUB_HOSTED_URL env var.
    steps:
      - run: |
          echo 'unset PUB_HOSTED_URL' >> $BASH_ENV
          source $BASH_ENV

jobs:
  format_analyze:
    executor: docker-executor
    steps:
      - install_flutter
      - checkout
      - install_melos
      - run: melos run format
      - run:
          name: Validate formatting
          command: ./.circleci/validate_formatting.sh
      - run: melos run analyze

  unit_test_flutter:
    executor: docker-executor
    steps:
      - reset_pub_url
      - install_flutter
      - checkout
      - install_melos
      - run:
          name: Install junitreport for JUnit XML reports
          command: flutter pub global activate junitreport
      - run:
          name: Run Flutter Unit Tests
          command: melos run test:unit:flutter
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex "\./packages/.*/test-results/.*-flutter-test\.xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  unit_test_ios:
    executor: macos-executor
    steps:
      - install_flutter:
          flutter_branch: 1.17.5
      - checkout
      - install_melos
      - run:
          name: Pre-start iOS simulator
          # xcrun instruments returns non zero, but successfully starts the simulator
          command: xcrun instruments -w "iPhone 11 (13.6) [" || true
      - run:
          name: Run iOS Unit Tests
          command: ./.circleci/test_all_plugins.sh ios-test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex "\./packages/.*/example/ios/test-results/.*-xcodebuild-test\.xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  unit_test_android:
    executor: docker-executor
    steps:
      - reset_pub_url
      - install_flutter
      - checkout
      - install_melos
      - run:
          name: Build example APKs
          command: |
            melos run build:examples:android
      - run:
          name: Run Android Unit Tests
          command: melos run test:unit:android
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex "\./packages/.*/example/build/.*/test-results/.*\.xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  integ_e2e_test_placeholder:
    executor: docker-executor
    steps:
      - run: |
          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
            echo "No AWS_ACCESS_KEY_ID is set! Failing..."
            exit 1;
          else
            echo "Credentials are available. Continuing..."
          fi
      - run: echo "TODO Integration/e2e test placeholder."

  push_fork_to_upstream_branch:
    executor: docker-executor
    steps:
      - run: echo "TODO Push fork to upstream branch to run further testing."

  publish_unstable:
    executor: publish-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - b5:9f:aa:92:c9:a2:7e:d4:66:ea:dd:ab:66:4e:fe:f4
      - aws-white-list-circleci-ip/add:
          port: 4000
      - install_flutter
      - checkout
      - write_oauth_tokens
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec fastlane unstable
      - aws-white-list-circleci-ip/remove:
          port: 4000

  push_to_release:
    executor: docker-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - b5:9f:aa:92:c9:a2:7e:d4:66:ea:dd:ab:66:4e:fe:f4
      - checkout
      - run: git checkout release && git merge master
      - run: git push origin release

  publish_stable:
    executor: publish-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - b5:9f:aa:92:c9:a2:7e:d4:66:ea:dd:ab:66:4e:fe:f4
      - aws-white-list-circleci-ip/add:
          port: 4000
      - install_flutter
      - checkout
      - write_oauth_tokens
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec fastlane stable
      - aws-white-list-circleci-ip/remove:
          port: 4000

releasable_branches: &releasable_branches
  branches:
    only:
      - release
      - master

workflows:
  test_deploy:
    jobs:
      - unit_test_flutter:
          filters:
            branches:
              ignore:
                - release
                - trigger-integration
      - unit_test_android:
          filters:
            branches:
              ignore:
                - release
                - trigger-integration
      - request_further_testing:
          type: approval
          filters:
            branches:
              only:
                - /pull\/[0-9]+/
      - integ_e2e_test_placeholder:
          filters:
            branches:
              ignore:
                - /pull\/[0-9]+/
      - push_fork_to_upstream_branch:
          requires:
            - request_further_testing
      - request_publish_unstable:
          type: approval
          requires:
            - unit_test_flutter
            - unit_test_android
            - integ_e2e_test_placeholder
          filters:
            branches:
              only:
                - master
      - publish_unstable:
          requires:
            - request_publish_unstable
      - request_publish_stable:
          type: approval
          requires:
            - publish_unstable
      - push_to_release:
          requires:
            - request_publish_stable
      - publish_stable:
          filters:
            branches:
              only:
                - release
